### ISSUE TITLE
Execution time.

### ISSUE THREAD

**Issue by nprithviraj24** [uttejh/opencl#2]
<strong>Where:</strong>
<br />
To check the optimality of code, we are using time function to determine the latency of the code. 
<br />
<strong>Issue</strong>
<br />
Execution time is not varying when a new function/module is injected to the code. This doesn't explain many intricacies involved in Parallel processing.
<br />

**Comment by uttejh** [comment]
done. The problem was inside the kernel. I had to change float to double
